---
- name: create app database
  postgresql_db: >-
    name={{ postgresql_database_name }}
    encoding=UTF-8
    login_host={{ postgresql_login_host }}
    login_user={{ postgresql_login_user }}
    login_password={{ postgresql_login_password }}
    template=template0
    state=present

- name: configure extensions
  postgresql_ext: >-
    name={{ item }}
    db={{ postgresql_database_name }}
    login_host={{ postgresql_login_host }}
    login_user={{ postgresql_login_user }}
    login_password={{ postgresql_login_password }}
    state=present
  with_items: "{{ postgresql_enable_extensions }}"

- name: create database role for app
  postgresql_user: >-
    name={{ postgresql_role_name }}
    password={{ postgresql_role_password }}
    db={{ postgresql_database_name }}
    priv=CONNECT
    login_host={{ postgresql_login_host }}
    login_user={{ postgresql_login_user }}
    login_password={{ postgresql_login_password }}
    state=present

- name: grant privileges for app role
  postgresql_privs: >-
    role={{ postgresql_role_name }}
    db={{ postgresql_database_name }}
    objs=ALL_IN_SCHEMA
    priv={{ postgresql_priv }}
    type=table
    login_host={{ postgresql_login_host }}
    login_user={{ postgresql_login_user }}
    login_password={{ postgresql_login_password }}
    state=present
