---
- name: Prepare
  hosts: all
  tasks:
    - name: install os dependencies
      apt: name={{ packages }} state=present
      vars:
        packages:
          - postgis
          - postgresql
          - python-psycopg2

    - name: ensure postgresql server is started
      service: name=postgresql state=started enabled=true

    - name: create a master db user for the test
      postgresql_user: name=master_user role_attr_flags=SUPERUSER password=masterpassword state=present
      become: true
      become_user: postgres

    - name: create a db for the master user for the test
      postgresql_db: name=master_user owner=master_user state=present
      become: true
      become_user: postgres

    - name: enable network login for postgres user
      lineinfile: >-
        dest=/etc/postgresql/9.3/main/pg_hba.conf
        line="host    all             all              127.0.0.1/32            trust"
      when: ansible_distribution_release == "trusty"

    - name: enable network login for postgres user
      lineinfile: >-
        dest=/etc/postgresql/10/main/pg_hba.conf
        line="host    all             all              127.0.0.1/32            trust"
      when: ansible_distribution_release != "trusty"
