---
- name: Prepare
  hosts: all
  tasks:
    - name: install local postgresql server
      apt: name=postgresql state=present

    - name: install ansible requirements
      pip: name=pyscopg2 state=present

    - name: enable network login for postgres user
      lineinfile: >-
        dest=/etc/postgresql/9.3/main/pg_hba.conf
        line="local   all             all          127.0.0.1/32              peer"
      when: ansible_distribution_release == "trusty"

    - name: enable network login for postgres user
      lineinfile: >-
        dest=/etc/postgresql/10/main/pg_hba.conf
        line="local   all             all          127.0.0.1/32              peer"
      when: ansible_distribution_release != "trusty"
